all: sigint

sigint: sigint.c
	gcc csapp.c csapp.h sigint.c
run_sigint: sigint
	./sigint
snooze: snooze.c
	gcc csapp.c csapp.h snooze.c
setjump:
	gcc csapp.h setjump.c
restart:
	gcc csapp.c csapp.h restart.c
clean:
	rm sigint